language: java
jdk:
  - oraclejdk8
  - oraclejdk11
  - oraclejdk-ea
matrix:
  # Allow failures with early access JDKs
  allow_failures:
    - jdk: openjdk-ea
script:
  # Install dependencies and build project
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  # Run tests
  - mvn test -B
